#ifndef PINAGEM_H
#define PINAGEM_H

#define PIN_EIXO_X_JOYSTICK_DIREITA 34
#define PIN_EIXO_Y_JOYSTICK_DIREITA 35
#define PIN_SW_JOYSTICK_DIREITA 17
#define PIN_EIXO_X_JOYSTICK_ESQUERDA 36
#define PIN_EIXO_Y_JOYSTICK_ESQUERDA 39
#define PIN_SW_JOYSTICK_ESQUERDA 16
#define PIN_INCREMENTO 33
#define PIN_DECREMENTO 25
#define PIN_APLICAR_E_RESET 32
#define PIN_LED_CONEXAO_FALHOU 26
#define PIN_LED_CONEXAO_BEM_SUCEDIDA 27

inline void configurarPinos() {
  pinMode(PIN_INCREMENTO, INPUT_PULLUP);
  pinMode(PIN_DECREMENTO, INPUT_PULLUP);
  pinMode(PIN_EIXO_X_JOYSTICK_ESQUERDA, INPUT_PULLUP);
  pinMode(PIN_EIXO_Y_JOYSTICK_ESQUERDA, INPUT_PULLUP);
  pinMode(PIN_APLICAR_E_RESET, INPUT_PULLUP);
  pinMode(PIN_SW_JOYSTICK_DIREITA, INPUT_PULLUP);
  pinMode(PIN_SW_JOYSTICK_ESQUERDA, INPUT_PULLUP);
  pinMode(PIN_LED_CONEXAO_FALHOU, OUTPUT);
  pinMode(PIN_LED_CONEXAO_BEM_SUCEDIDA, OUTPUT);
}

#endif